### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by nwilliams98** [Project-Platypus/J3Py#1]
Hi I tried using your J3 from python.  After installing j3py with: python setup.py install
I get this error:
error" package directory 'j3' does not exist.

then i am able to use:
from j3 import J3 

but:

 J3()

Gives the error below---------------------------------------------------------------------
Traceback (most recent call last):

  File "<ipython-input-7-e717f910ec9a>", line 1, in <module>
    J3()

  File "C:\ProgramData\Anaconda3\lib\site-packages\j3py-1.0-py3.6.egg\j3\__init__.py", line 71, in J3
    raise RuntimeError("Unable to locate or download J3")

RuntimeError: Unable to locate or download J3

**Comment by dhadka** [comment]
Hi, thanks for reporting this.  I unfortunately didn't have this project watched so never got a notification about this issue.  It's fixed now.
