### ISSUE TITLE
Seeking help

### ISSUE THREAD

**Issue by lucdq** [Project-Platypus/J3Py#2]
After downloading J3Py into PyCharm and running the code, the following error appears. How should I resolve it?
_Unable to access latest release info on github.com
Traceback (most recent call last):
  File "rhodiumRDM\visualization_with_J3.py", line 86, in <module>
    J3(output.as_dataframe(list(model.responses.keys())))
  File "site-packages\j3\__init__.py", line 55, in J3
    install_dir = os.path.join(j3_dir, id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 147, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'_

**Comment by dhadka** [comment]
Hi, I'm archiving this project as it was original written for Python 2 and no longer works with recent updates made to J3.  I've updated the README to provide guidance, which is to save the data to a CSV or other file format, then open it in J3.
